language: android

git:
        submodules: false

node_js:
  - 5.5

notifications:
  email: false

sudo: false

branches:
  only:
  - master

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - npm cache clean
  - npm install
  - npm install -g cordova
  - echo y | android update sdk -u --filter android-22,android-2

before_script:
  - cordova platform rm android
  - cordova platform add android

script:
  - cordova prepare
  - cordova build android
  
release:
  - exit 0  
